### ISSUE TITLE
feat: lock template preview endpoint behind authentication

### ISSUE THREAD

**Issue by wa0x6e** [snapshot-labs/envelop#12]
Template preview should be reserved for internal use only, and not accessible by a regular user

authentication method tbd

- basic authentication
- verification of auth query params set in .env
- web3

**Comment by wa0x6e** [comment]
The previewer currently use query params to enable customization, so we can view email for a different subscriber, and address.

In production, this may leak some personal data, like in the verification email.

If we want to keep it public, query params customization should be removed from template previewer

**Comment by wa0x6e** [comment]
One potential feature we could add after adding authentication, is to have a "TEST SEND" button directly on the preview page, to test sending the email

**Comment by bonustrack** [comment]
Would be simpler if we dont need to do authentication, we could add a way to send test email to custom email + custom address(es)

**Comment by wa0x6e** [comment]
In that case, we should remove the query params such as `?address=xxx&to=yyyy`, and drop the ability to test the email for a particular address/email

**Comment by bonustrack** [comment]
Sound good
