### ISSUE TITLE
bug: deployment failing

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#19]
Deployment are failing on DigitalOcean with this error:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/16245250/224538312-7f00959e-25da-4c13-a455-a7f34482e0d2.png">

**Comment by wa0x6e** [comment]
Should already be fixed via #16

**Comment by bonustrack** [comment]
Closing this issue, this is not relevant anymore.
