### ISSUE TITLE
feat: summary email should recurring weekly

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#3]
We should send email to subscribers once a week, the implementation should assume the server may go down when sending emails.

**Comment by wa0x6e** [comment]
Proposed implementation:

- Use a cron job to trigger sending script once a week
- sending script will get all the subscribers, and put all the emails in a queue 
- the queue system will process and send each email one by one

Queue system will avoid having to send all emails at once in one long task, with each sending task having a `retry` function, in case of error, with an exponential backoff strategy

We should also have a dedicated database table to track each emails status, to track delivery and avoid duplicate.

**Comment by wa0x6e** [comment]
Bull (https://github.com/OptimalBits/bull#readme) seems to be the more popular nodejs option for the queue system.

Should we proceed with the queue option, or do you have another implementation in mind ?
