### ISSUE TITLE
feat: add subscribe form to snapshot.org

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#35]
After someone cast a vote on snapshot.org we should show a form with an input to add an email for user to subscribe to summary

**Comment by wa0x6e** [comment]
Should we add an endpoint first, to check if the user is already subscribed ?

**Comment by bonustrack** [comment]
No, we wouldnt know if someone subscribed cuz wallet are not verified, someone could subscribe with a wallet he dont own (using Guest.so for example) or someone may want subscribe with a different email address for same wallet.

**Comment by bonustrack** [comment]
Yes, and yes. Later we would validate Ethereum address and hide the form.

**Comment by wa0x6e** [comment]
Are you saying that anyone can cast a vote with a wallet he don't own ?

**Comment by wa0x6e** [comment]
Moving the discussion to snapshot repo: https://github.com/snapshot-labs/snapshot/pull/3754
