### ISSUE TITLE
feat: send confirmation email

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#4]
When someone subscribe to the summary emails we should verify his email by sending him a confirmation email using a link with a code generated from an Ethereum signature.

**Comment by wa0x6e** [comment]
Who is hosting the landing page the verification link is linking to ? 

snapshot.org or do we create a landing page on envelop.fyi side ?

**Comment by bonustrack** [comment]
We can have a simple Vue.js app on https://github.com/snapshot-labs/envelop-ui based on sx-ui setup (without the layout or Electron)

**Comment by wa0x6e** [comment]
> We can have a simple Vue.js app on https://github.com/snapshot-labs/envelop-ui based on sx-ui setup (without the layout or Electron)

So this vue app will handle the landing page when:
- the user click on the verify email link
- the user click on the unsubscribe link

Does it also handle the subscription itself (add email+address form), or will it be integrated in the snapshot profile page ?

**Comment by bonustrack** [comment]
> Does it also handle the subscription itself (add email+address form), or will it be integrated in the snapshot profile page ?

@wa0x6e It will be handled on Snapshot.org

We may also later verify the wallet using the UI

**Comment by wa0x6e** [comment]
Should the address be verified for each [email, address] couple, on only once for the email, regardless of the address ?
