### ISSUE TITLE
feat: preview for email templates

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#5]
Currently the only way to see the email template is to send an email, we should instead have a simple way to display an email template without sending email.

**Comment by wa0x6e** [comment]
Should the preview feature replace the actual email sending when enabled (like when on local env), or should it co-exists with a live sending ?

**Comment by wa0x6e** [comment]
See PR https://github.com/snapshot-labs/envelop/pull/9

**Comment by wa0x6e** [comment]
Closed via #9
