### ISSUE TITLE
feat: remove redundant sending subscription email

### ISSUE THREAD

**Issue by Todmy** [snapshot-labs/envelop#57]
related to #55 ([initial discussion](https://github.com/snapshot-labs/envelop/pull/55#issuecomment-1545698457))

🟢 ER: We should send a subscription confirmation email only if the user's subscription doesn't exist in DB. Otherwise, it shouldn't be sent.

🔴 AR: Each time when a user subscribes, we send a subscription confirmation email. It's insecure since everyone can use it to cause harm to the company by sending dozen of emails, which can increase our payment for email-sending service.

**Comment by wa0x6e** [comment]
Should be fixed via #46
