### ISSUE TITLE
feat: show proposal short description on summary

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/envelop#8]
This will require removing the markdown format from a proposal body see example here: https://github.com/snapshot-labs/snapshot/blob/1cda59cce173aec6ac2286d5f602478452c02725/src/components/ProposalsItem.vue#L3

**Comment by wa0x6e** [comment]
How should we truncate the text ? By a fixed number or characters/words ? 

I would avoid relying on CSS for truncation, as their CSS support is poor.

**Comment by bonustrack** [comment]
@wa0x6e By number of chars, you can keep the same amount of text than on snapshot.org proposal preview
